version: "3"

services:

    shopware:
        image: dockware/dev:<VERSION/latest>
        environment:
            - PHP_VERSION=<VERSION>
        container_name: SW6_<NAME>
        ports:
            - "80:80"
            - "22:22"
        volumes:
            - "<LOCAL_PATH>:<DOCKER_PATH>"
        networks:
            - web

networks:
    web:
        external: false
